const names = ["Ahri","Alistar","Amumu","Anivia","Annie","Ashe","Blitzcrank","Brand","Cho'Gath","Corki","Dr. Mundo","Evelynn","Ezreal","Fiddlesticks","Gangplank","Garen","Gragas","Heimerdinger","Janna","Jarvan IV","Jax","Karthus","Kassadin","Katarina","Kayle","Kog'Maw","Lee Sin","Leona","Lulu","Lux","Malphite","Malzahar","Master Yi","Miss Fortune","Morgana","Nasus","Nidalee","Nunu & Willump","Olaf","Pantheon","Rammus","Ryze","Shaco","Sion","Singed","Sivir","Skarner","Sona","Soraka","Taric","Teemo","Tristana","Tryndamere","Twisted Fate","Twitch","Vayne","Veigar","Warwick","Wukong","Zilean"];
const body=document.querySelector('#body'),status=document.querySelector('#status'),fill=document.querySelector('#fill'),check=document.querySelector('#check'),loadButton=document.querySelector('#load'),settingsButton=document.querySelector('#gear');
const emblem='../assets/rift-rank-emblem.png',emblemLarge='../assets/rift-rank-emblem-large.png';
const rankEmblems={salt:'../assets/rift-rank-salt.png',wood:'../assets/rift-rank-wood.png',silver:'../assets/rift-rank-silver.png',gold:'../assets/rift-rank-gold.png',plat:'../assets/rift-rank-platinum.png',platinum:'../assets/rift-rank-platinum.png',diamond:'../assets/rift-rank-diamond.png',legend:'../assets/rift-rank-legend.png'};
let lastState=null,loadState='idle',updateReady=false,prefs={LoadingScreen:true,DisabledChampions:[],AvailablePackages:[]};
const norm=s=>String(s).toLowerCase().replace(/[^a-z0-9]/g,'').replace('nunuandwillump','nunu');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const displayName=s=>String(s??'').split('#')[0].trim();
function rankEmblem(rank,large=false){const tier=String(rank||'').trim().split(/\s+/)[0].toLowerCase().replace(/[^a-z]/g,'');return rankEmblems[tier]||(large?emblemLarge:emblem)}
function profile(p){return `<section class="profile"><div class="identity"><div class="summoner">${esc(displayName(p.name))}</div><img src="${rankEmblem(p.rank,true)}"><div class="rank">${esc(p.rank)}</div></div><div class="metrics">${metric('LP',p.lp)}${metric('WINS',p.wins,'good')}${metric('LOSSES',p.losses,'bad')}${metric('WIN RATE',p.winrate+'%',p.winrate>=50?'good':'bad')}</div></section>`}
function metric(k,v,c=''){return `<div class="metric"><label>${k}</label><b class="${c}">${v}</b></div>`}
function streakBadge(streak){const n=Number(streak||0);if(n>=3)return `<span class="streak win">🔥 ${n} win streak</span>`;if(n<=-3)return `<span class="streak loss">❄ ${Math.abs(n)} loss streak</span>`;return ''}
function winRateStyle(rate){const wr=Number(rate||0);if(wr>=70)return ['linear-gradient(90deg,#e8a020,#d6791e)','rgba(214,121,30,.18)'];if(wr>=60)return ['linear-gradient(90deg,#2a86ad,#1c6f96)','rgba(28,111,150,.18)'];if(wr>=50)return ['linear-gradient(90deg,#2a9c54,#1b6e2f)','rgba(27,110,47,.16)'];return ['linear-gradient(90deg,#9a9282,#6f685a)','rgba(110,104,90,.18)']}
function player(p){const [bar,track]=winRateStyle(p.winrate);return `<div class="player"><img src="${rankEmblem(p.rank)}"><div><div class="phead"><span class="pname">${esc(displayName(p.name))}</span>${streakBadge(p.streak)}</div><div class="pchamp">${esc(p.champion)} · ${esc(p.rank)}</div></div><div class="pstats"><div class="record"><span class="plp">${p.lp} LP</span> · ${p.wins}W/${p.losses}L</div><div class="wrbar" style="background:${track}"><div class="wrfill" style="width:${Math.max(0,Math.min(100,Number(p.winrate||0)))}%;background:${bar}"></div><span class="wrtext">${p.winrate}%</span></div></div></div>`}
function sectionTitle(){return `<div class="section-title"><i></i><h2>CURRENT GAME</h2><i></i></div>`}
function render(s){lastState=s;const connected=Boolean(s.client);settingsButton.disabled=!connected||!updateReady;loadButton.disabled=!connected||!updateReady||loadState==='loading';if(!connected){modal.classList.remove('open');body.innerHTML=`<div class="offline"><div class="warning">⚠</div><h1>LEAGUE OF LEGENDS IS NOT RUNNING</h1><p>Please launch <b>League of Legends</b> to use <b>Rift Legacy</b>.</p><div class="waiting">● &nbsp; WAITING FOR GAME CLIENT…</div></div>`;return}const game=s.game?`<div class="game-meta"><span>Summoner's Rift · Jade</span><span>Duration: ${Math.floor(s.gameTime/60)}:${String(Math.floor(s.gameTime%60)).padStart(2,'0')}</span></div><div class="teams">${team('BLUE SIDE','blue',s.players.filter(p=>p.team==='ORDER'))}${team('RED SIDE','red',s.players.filter(p=>p.team!=='ORDER'))}</div>`:`<div class="empty"><div class="hour">⌛</div><strong>NO GAME IN PROGRESS</strong><span>Automatically detecting active games…</span></div>`;body.innerHTML=sectionTitle()+game+profile(s.profile)}
function team(title,cls,players){return `<section class="team ${cls}"><h3>${title}</h3><div class="roster">${players.map(player).join('')}</div></section>`}
async function poll(){try{render(await window.rift.state())}catch{}setTimeout(poll,1000)}
document.querySelector('#min').onclick=()=>window.rift.minimize();document.querySelector('#max').onclick=()=>window.rift.maximize();document.querySelector('#close').onclick=()=>window.rift.close();
loadButton.onclick=async()=>{if(!updateReady||!lastState?.client||loadState==='loading')return;let n=0;loadState='loading';loadButton.disabled=true;settingsButton.disabled=true;pbePathButton.disabled=true;status.textContent='LOADING LTK & SELECTED ASSETS...';check.textContent='●';check.style.color='#c8aa6e';const timer=setInterval(()=>{n=Math.min(95,n+1);fill.style.width=n+'%'},180);const result=await window.rift.load();clearInterval(timer);if(result.ok){loadState='active';fill.style.width='100%';status.textContent='CLASSIC & DEFAULT SKINS ACTIVE';check.textContent='✓';check.style.color='#54d0e0';loadButton.textContent='RELOAD'}else{loadState='error';status.textContent='ERROR · '+(result.message||'LTK');check.textContent='×';check.style.color='#d85a4a';fill.style.width='0%'}const connected=Boolean(lastState?.client);loadButton.disabled=!connected;settingsButton.disabled=!connected;pbePathButton.disabled=false};
const modal=document.querySelector('#modal');settingsButton.onclick=()=>{if(updateReady&&lastState?.client&&loadState!=='loading')modal.classList.add('open')};document.querySelector('#modalClose').onclick=async()=>{const disabled=[];champions.querySelectorAll('input').forEach(input=>{if(!input.checked){const found=(prefs.AvailablePackages||[]).find(p=>norm(p.replace(/-(classic|base)$/,''))===norm(input.dataset.name));if(found)disabled.push(found)}});prefs.LoadingScreen=document.querySelector('#loading').checked;prefs.DisabledChampions=disabled;await window.rift.savePreferences(prefs);modal.classList.remove('open')};
const helpModal=document.querySelector('#helpModal');document.querySelector('#help').onclick=()=>helpModal.classList.add('open');document.querySelector('#helpClose').onclick=()=>helpModal.classList.remove('open');helpModal.onclick=e=>{if(e.target===helpModal)helpModal.classList.remove('open')};
const pbePathButton=document.querySelector('#pbePath'),pbePathValue=document.querySelector('#pbePathValue');pbePathButton.onclick=async()=>{const result=await window.rift.selectPbePath();if(result?.ok){pbePathValue.textContent=result.path;pbePathValue.title=result.path;status.textContent='PBE PATH UPDATED · READY TO LOAD'}};
function applyUpdateState(state){const phase=state?.phase||'checking';updateReady=phase==='ready';status.textContent=state?.message||(updateReady?'READY TO LOAD':'CHECKING FOR UPDATES...');if(phase==='downloading'||phase==='applying'){fill.style.width=Number(state.progress||0)+'%';check.textContent='↓';check.style.color='#c8aa6e'}else if(!updateReady){fill.style.width='0%';check.textContent='●';check.style.color='#c8aa6e'}else if(loadState==='idle'){fill.style.width='0%';check.textContent='●';check.style.color='#5b5a56'}const connected=Boolean(lastState?.client);loadButton.disabled=!updateReady||!connected||loadState==='loading';settingsButton.disabled=!updateReady||!connected;pbePathButton.disabled=!updateReady||loadState==='loading'}
const champions=document.querySelector('#champions');names.forEach(n=>champions.insertAdjacentHTML('beforeend',`<label><input type="checkbox" data-name="${n}" checked> ${n}</label>`));
document.querySelector('#all').onclick=()=>champions.querySelectorAll('input').forEach(x=>x.checked=true);document.querySelector('#none').onclick=()=>champions.querySelectorAll('input').forEach(x=>x.checked=false);
(async()=>{loadButton.disabled=true;settingsButton.disabled=true;pbePathButton.disabled=true;status.textContent='CHECKING FOR UPDATES...';check.textContent='●';check.style.color='#c8aa6e';fill.style.width='0%';window.rift.onUpdateStatus(applyUpdateState);applyUpdateState(await window.rift.updateState());const configured=await window.rift.pbePath();if(configured?.path){pbePathValue.textContent=configured.path;pbePathValue.title=configured.path}prefs=await window.rift.preferences();document.querySelector('#loading').checked=prefs.LoadingScreen!==false;champions.querySelectorAll('input').forEach(input=>{const found=(prefs.AvailablePackages||[]).find(p=>norm(p.replace(/-(classic|base)$/,''))===norm(input.dataset.name));input.checked=!found||!(prefs.DisabledChampions||[]).includes(found)});poll()})();
